version: '3'
services:
  app:
    container_name: tolgee_js_e2e_server
    image: tolgee/tolgee:latest
    ports:
      - 8202:8080
      - 8092:8091
    environment:
      - tolgee.internal.populate=true
      - tolgee.authentication.enabled=true
      - tolgee.internal.controllerEnabled=true
      - 'tolgee.screenshots-url=http://localhost:8202/screenshots'
      - tolgee.authentication.needs-email-verification=true
      - tolgee.authentication.registrations-allowed=true
      - tolgee.internal.fake-emails-sent=true
      - tolgee.authentication.initialPassword=admin
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8091,server=y,suspend=n
  e2e_app_core:
    container_name: tolgee_js_e2e_serve_testapps_core
    build: ../docker
    volumes:
      - '../testapps/core:/data'
    ports:
      - 8101:8101
    command: ['npm', 'run', 'serve']
    working_dir: /data
  e2e_app_react:
    container_name: tolgee_js_e2e_serve_testapps_react
    build: ../docker
    volumes:
      - '../:/data'
    ports:
      - 8102:8101
    command: ['npm', 'run', 'serve']
    working_dir: /data/testapps/react
  e2e_app_angular:
    container_name: tolgee_js_e2e_serve_testapps_ngx
    build: ../docker
    volumes:
      - '../:/data'
    ports:
      - 8103:8101
    command: ['npm', 'run', 'serve']
    working_dir: /data/testapps/ngx
