version: '3'
services:
  app:
    container_name: tolgee
    image: tolgee/tolgee:${TEST_TOLGEE_SERVER_VERSION}
    ports:
      - '${TEST_TOLGEE_API_PORT}:8080'
    environment:
      - app.populate=true
